# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 34dfcb214bec1ab1a09efc1d19006f5ffb8ff5020925be04f9376b6f210e82efebb333c7108dbcaddd603aad03b4f0566a8bbf12b7f49110b1d684674992ef3b

test:
  secret_key_base: e8ceb1e71e6a0fa7d813ea49e6d4589144f7549439320036a47a8e118fa41ee72870b4bea8e75096e61af83147c65da50784e14401348493929922c2d135df9f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
